### ISSUE TITLE
Tor 0.5.3.* support

### ISSUE THREAD

**Issue by dballard** [n8fr8/tor-android#9]
When using to build tor 0.3.5.3-alpha I get the error `cp: cannot stat 'tor/src/or/tor': No such file or directory` (full trace below)

It looks like tor did some code restructure between 0.3.4 and 0.3.5 and dropped the `src/or` directory entirely, so the Makefile is going to need some updating to support this

```
  CC       src/test/fuzz/src_test_fuzz_fuzz_vrs-fuzzing_common.o
  CC       src/test/fuzz/src_test_fuzz_fuzz_vrs-fuzz_vrs.o
  CCLD     src/test/fuzz/fuzz-vrs
make[1]: Leaving directory '/home/dan/src/projects/tor-reproducer/tmp/tor-android/external/tor'
touch tor-build-stamp
test -d bin || mkdir bin
cp tor/src/or/tor bin
cp: cannot stat 'tor/src/or/tor': No such file or directory
Makefile:273: recipe for target 'tor' failed
make: *** [tor] Error 1
make: Leaving directory '/home/dan/src/projects/tor-reproducer/tmp/tor-android/external'
Traceback (most recent call last):
  File "./../build-tor.py", line 278, in <module>
    main()
  File "./../build-tor.py", line 30, in main
    build_android()
  File "./../build-tor.py", line 149, in build_android
    build_android_arch('tor_arm_pie.zip')
  File "./../build-tor.py", line 169, in build_android_arch
    check_call(['make', '-C', 'external', 'clean', 'tor'], cwd=REPO_DIR)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', 'external', 'clean', 'tor']' returned non-zero exit status 2.
```

**Comment by dballard** [comment]
**Move literally everything out of src/or**
https://gitweb.torproject.org/tor.git/commit/?h=tor-0.3.5.3-alpha&id=63b4ea22af8e8314dd718f02046de5f4b91edf9d
